### ISSUE TITLE
lecture Notes Optimization 

### ISSUE THREAD

**Issue by alialrafei** [DrWaleedAYousef/Teaching#3]
There is a typo in the title of the lecture notes also the course ID is it CS495 or CS395

Thanks in advance Dr waleed .

**Comment by DrWaleedAYousef** [comment]
Where exactly? Which page?

**Comment by alialrafei** [comment]
First page in the lecture notes the cover page .

**Comment by DrWaleedAYousef** [comment]
Oh; the title; the course name itself. Very funny :) Thanks so much

**Comment by alialrafei** [comment]
you are welcome dr waleed.
