### ISSUE TITLE
Pattern Recognition course link redirects to another Youtube channel

### ISSUE THREAD

**Issue by Mohammed-Ashour** [DrWaleedAYousef/Teaching#6]
Hi Prof Waleed,
First, Thanks for your great contributions

The Issue :  
in this page (Pattern Recognition course directory in this repo)
https://github.com/DrWaleedAYousef/Teaching/blob/master/PatternRecognition/README.md
video lectures link :  
http://www.youtube.com/course?list=ECoK2Lr1miEm9scZv7zSAMENjMhcMMH2cU
redirects to this channel   
https://www.youtube.com/channel/UCPGhc5lTBhxd54hdFEvhm-g

I think it can be fixed by replacing the previous link with this one 
https://www.youtube.com/playlist?list=PLoK2Lr1miEm9scZv7zSAMENjMhcMMH2cU

**Comment by DrWaleedAYousef** [comment]
Thanks so much; fixed.

**Comment by DrWaleedAYousef** [comment]
I am very surprised because I found the same strange link is went viral to other courses as well!! I just corrected all of them. Thanks again.

**Comment by Mohammed-Ashour** [comment]
Not at all. 
Thank you for your great educational content!  

About the issue, after reviewing the commit log, I seems that the link was there from the first Init commit 
https://github.com/DrWaleedAYousef/Teaching/commit/195813c7ded5ded6e7a8a95b2bc98552d139ce59#diff-1dee08f2c0dffd57de02570690e50d1c697a1b44bbe2e9ff7a2deed9ebbbe4fe

Maybe Youtube changed the way the site handles some types of links or something and was redirecting to the playlist at first but now redirects to the most matched channel name/ID  which was Ironically  "Course"
